// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Certificate struct {
	CertificateID string
	TemplateID    int32
	CourseID      int32
	StudentID     int32
	Timestamp     pgtype.Timestamptz
	Data          []byte
}

type Course struct {
	CourseID int32
	Data     []byte
}

type Student struct {
	StudentID int32
	Data      []byte
}

type Template struct {
	TemplateID int32
	Content    string
}
